package logic;

import java.awt.Color;
import java.util.Random;

/**
 * This class contains the secret color combination generated by the computer
 * @author Fabiana Arias y Fabian Alfaro
 *
 */
public class SecretCombination {
	
	private int combinationLength = 4;
	
	Colors colors = new Colors();
	
	private Color[] secretCombination = {Color.white, Color.white, Color.white, Color.white};
	
	Random randomMethod = new Random();
	
	
	/**
	 * Constructor method
	 */
	public SecretCombination() {}
	

	/**
	 * Method that gets a random color from the list of default colors
	 * @return A random color
	 */
	public Color getRandomColor() {
		
		Color[] colorsList = colors.getColors();
	    int index = randomMethod.nextInt(colorsList.length);
	    //System.out.println("Random Element is :"+ colorsList[index]);
	    
	    return colorsList[index];
	}
	
	
	
	/**
	 * Method that generates a secret combination with random colors
	 */
	public void generateSecretCombination() {
		int i=0;
		while (i < combinationLength) {
			this.secretCombination[i] = this.getRandomColor();
			System.out.println(secretCombination[i]);
			i++;
		}
		
	}
	
	
	/**
	 * Method that returns the generated secret combination
	 * @return ArrayList of colors with the secret combination
	 */
	public Color[] getSecretCombination() {
		//System.out.println(secretCombination);
		return this.secretCombination;
	}
}
